/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package servidor;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.Socket;

/**
 *
 * @author C.MORAGA
 */
public class ChatServidor extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ChatServidor.class.getName());
    private BufferedReader br;
    private BufferedWriter bw;
    private Socket socket;
    private Thread hiloLectura;
    private boolean activo = true;
    
    /**
     * Creates new form ChatServidor
     */
    public ChatServidor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();     
    }
    
    public ChatServidor(java.awt.Frame parent, boolean modal, Socket socket) {
        super(parent, modal);
        this.socket = socket;
        initComponents();
        
        try {
            br = new BufferedReader(new InputStreamReader(socket.getInputStream()));
            bw = new BufferedWriter(new OutputStreamWriter(socket.getOutputStream()));
        

            iniciarLectura();
        } catch (IOException ex) {
            logger.log(java.util.logging.Level.SEVERE, "Error al configurar streams", ex);
            cerrarConexion();        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTServidorConversacion = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTServidorRespuesta = new javax.swing.JTextArea();
        bEnviar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTServidorConversacion.setColumns(20);
        jTServidorConversacion.setRows(5);
        jTServidorConversacion.setEnabled(false);
        jScrollPane1.setViewportView(jTServidorConversacion);

        jTServidorRespuesta.setColumns(20);
        jTServidorRespuesta.setRows(5);
        jScrollPane2.setViewportView(jTServidorRespuesta);

        bEnviar.setText("Enviar");
        bEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEnviarActionPerformed(evt);
            }
        });

        jLabel1.setText("Introduzca su respuesta:");

        jLabel2.setText("CHAT CON CLIENTE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(bEnviar)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(bEnviar)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEnviarActionPerformed
        String respuesta = jTServidorRespuesta.getText().trim();
        
        if (!respuesta.isEmpty() && activo) {
            try {
                bw.write(respuesta + "\n");
                bw.flush();
                
                jTServidorConversacion.append("Servidor: " + respuesta + "\n");
                jTServidorRespuesta.setText("");
                
            } catch (IOException ex) {
                logger.log(java.util.logging.Level.SEVERE, "Error al enviar mensaje", ex);
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Error al enviar el mensaje.", 
                    "Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_bEnviarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrarConexion();
    }//GEN-LAST:event_formWindowClosing

    
    private void iniciarLectura() {
        hiloLectura = new Thread(() -> {
            try {
                String mensaje;
                while (activo && (mensaje = br.readLine()) != null) {
                    final String mensajeFinal = mensaje;
                    
                    // Actualizar UI en el EDT
                    javax.swing.SwingUtilities.invokeLater(() -> {
                        jTServidorConversacion.append("Cliente: " + mensajeFinal + "\n");
                    });
                }
            } catch (IOException ex) {
                // Solo registrar si es un error inesperado (no cierre normal)
                if (activo) {
                    logger.log(java.util.logging.Level.WARNING, "Conexión cerrada por el cliente", ex);
                }
            } finally {
                // Si el cliente cerró la conexión, cerrar todo
                if (activo) {
                    cerrarConexion();
                }
            }
        });
        hiloLectura.start();
    }
    
    private void cerrarConexion() {
        activo = false;
        try {
            if (socket != null && !socket.isClosed()) socket.close();
            if (br != null) br.close();
            if (bw != null) bw.close();
            
        } catch (IOException ex) {
            //logger.log(java.util.logging.Level.SEVERE, "Error al cerrar conexión", ex);
        }
        
        // Esperar a que termine el hilo de lectura
        if (hiloLectura != null && hiloLectura.isAlive()) {
            try {
                hiloLectura.join(1000);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
            }
        }
        
        javax.swing.SwingUtilities.invokeLater(() -> {
            dispose();
        });
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ChatServidor dialog = new ChatServidor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEnviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTServidorConversacion;
    private javax.swing.JTextArea jTServidorRespuesta;
    // End of variables declaration//GEN-END:variables
}
