/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package servidor;

import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;

/**
 *
 * @author C.MORAGA
 */
public class VentanaServidor extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaServidor.class.getName());
    private ServerSocket servidor;
    //private Socket socket;
    private boolean conectar = false;
    private Thread hiloServidor;
    /**
     * Creates new form VentanaServidor
     */
    public VentanaServidor() {
        initComponents();

        try {
            servidor = new ServerSocket(61000);   
        } catch (IOException ex) {
            System.getLogger(VentanaServidor.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bConectar = new javax.swing.JButton();
        bDesconectar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SERVICIO TÉCNICO");

        bConectar.setText("Conectar");
        bConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConectarActionPerformed(evt);
            }
        });

        bDesconectar.setText("Desconectar");
        bDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDesconectarActionPerformed(evt);
            }
        });

        jLabel2.setText("Desconectado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(233, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bConectar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bDesconectar)
                        .addGap(88, 88, 88))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bConectar)
                    .addComponent(bDesconectar))
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConectarActionPerformed
        if(!conectar){
            conectar = true;
            bConectar.setEnabled(false);
            
            // Crear hilo para escuchar clientes
            hiloServidor = new Thread(() -> {
                javax.swing.SwingUtilities.invokeLater(() -> {
                    jLabel2.setText("Esperando clientes...");
                });
                
                while(conectar) {
                    try {
                        Socket socket = servidor.accept();
                        System.out.println("Cliente conectado desde: " + socket.getInetAddress());
                        
                        // Actualizar UI en el EDT
                        javax.swing.SwingUtilities.invokeLater(() -> {
                            jLabel2.setText("Cliente conectado desde: " + socket.getInetAddress());
                            ChatServidor chatServidor = new ChatServidor(this, false, socket);
                            chatServidor.setVisible(true);
                        });
                        
                    } catch (IOException ex) {
                        if (conectar) { // Solo mostrar error si no fue cierre intencional
                            logger.log(java.util.logging.Level.SEVERE, "Error al aceptar conexión", ex);
                        }
                    }
                }
            });
            hiloServidor.start();
        } 
    }//GEN-LAST:event_bConectarActionPerformed

    private void bDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDesconectarActionPerformed
        conectar = false;
        bConectar.setEnabled(true);
        
        try {
            if (servidor != null && !servidor.isClosed()) {
                servidor.close();
                servidor = new ServerSocket(61000); // Recrear para futuras conexiones
            }
        } catch (IOException ex) {
            logger.log(java.util.logging.Level.SEVERE, "Error al cerrar servidor", ex);
        }
        
        jLabel2.setText("Desconectado");
        System.out.println("Ventana servidor desconectada");
    }//GEN-LAST:event_bDesconectarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaServidor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bConectar;
    private javax.swing.JButton bDesconectar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
