/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package servidor;

import java.awt.Toolkit;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;

/**
 *
 * @author C.MORAGA
 */
public class VentanaServidor extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaServidor.class.getName());
    private ServerSocket servidor;
    //private Socket socket;
    private boolean conectar = false;
    private Thread hiloServidor;
    /**
     * Creates new form VentanaServidor
     */
    public VentanaServidor() {
        initComponents();
        this.setTitle("SERVIDOR");
        // Ventana en esquina superior derecha
        int x = Toolkit.getDefaultToolkit().getScreenSize().width - this.getWidth();
        this.setLocation(x, 0);
        
        bDesconectar.setEnabled(false);
        
        try {
            servidor = new ServerSocket(61000);   
        } catch (IOException ex) {
            System.getLogger(VentanaServidor.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bConectar = new javax.swing.JButton();
        bDesconectar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SERVICIO TÉCNICO");

        bConectar.setText("Conectar");
        bConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConectarActionPerformed(evt);
            }
        });

        bDesconectar.setText("Desconectar");
        bDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDesconectarActionPerformed(evt);
            }
        });

        jLabel2.setText("Desconectado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bConectar)
                        .addGap(42, 42, 42)
                        .addComponent(bDesconectar))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bConectar)
                    .addComponent(bDesconectar))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConectarActionPerformed
        if(!conectar){
            conectar = true;
            bConectar.setEnabled(false);
            bDesconectar.setEnabled(true);
            // Crear hilo para escuchar clientes
            hiloServidor = new Thread(() -> {
                javax.swing.SwingUtilities.invokeLater(() -> {
                    jLabel2.setText("Esperando clientes...");
                });
                
                while(conectar) {
                    try {
                        Socket socket = servidor.accept();
                        System.out.println("Cliente conectado desde: " + socket.getInetAddress());
                        
                        // Actualizar UI en el EDT
                        javax.swing.SwingUtilities.invokeLater(() -> {
                            jLabel2.setText("Cliente conectado desde: " + socket.getInetAddress());
                            ChatServidor chatServidor = new ChatServidor(VentanaServidor.this, false, socket);
                            chatServidor.setVisible(true);
                            jLabel2.setText("Esperando clientes...");
                        });
                        
                    } catch (IOException ex) {
                        if (conectar) { // Solo mostrar error si no fue cierre intencional
                            logger.log(java.util.logging.Level.SEVERE, "Error al aceptar conexión", ex);
                        }
                    }
                }
            });
            hiloServidor.start();
        } 
    }//GEN-LAST:event_bConectarActionPerformed

    private void bDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDesconectarActionPerformed
        if(conectar){
            conectar = false;
            bConectar.setEnabled(true);
            bDesconectar.setEnabled(false);
            jLabel2.setText("Desconectando...");

    // Cerrar el servidor en un hilo separado para no bloquear
            new Thread(() -> {
                try {
                    if (servidor != null && !servidor.isClosed()) {
                        servidor.close();
                    }

                    // Esperar a que termine el hilo del servidor
                    if (hiloServidor != null && hiloServidor.isAlive()) {
                        hiloServidor.join(2000); // Esperar máximo 2 segundos
                    }

                    // Recrear el servidor para futuras conexiones
                    servidor = new ServerSocket(61000);

                    javax.swing.SwingUtilities.invokeLater(() -> {
                        jLabel2.setText("Desconectado");
                    });

                    System.out.println("Ventana servidor desconectada");

                } catch (IOException ex) {
                    logger.log(java.util.logging.Level.SEVERE, "Error al cerrar servidor", ex);
                    javax.swing.SwingUtilities.invokeLater(() -> {
                        jLabel2.setText("Error al desconectar");
                        bDesconectar.setEnabled(true);
                    });
                } catch (InterruptedException ex) {
                    logger.log(java.util.logging.Level.SEVERE, "Interrupción al esperar cierre", ex);
                    Thread.currentThread().interrupt();
                }
            }).start();
        }
    }//GEN-LAST:event_bDesconectarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaServidor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bConectar;
    private javax.swing.JButton bDesconectar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
